name: LobbyPvP
version: '1.0'
main: me.tamikkkkr.lobbyPvP.Plugin
softdepend: [DeluxeHub]
api-version: '1.21'
authors: [ ulik ]
description: LobbyPvP plugin - A sword that players can PvP each other with in the lobby!

commands:
  lobbypvp:
    aliases:
      - hubpvp
    description: LobbyPvP core command.
    permission: lobbypvp.reload
